/**:
  ros__parameters:
    sensor_hostname: '192.168.2.181'
    udp_dest: ''
    lidar_mode: ''
    timestamp_mode: ''
    point_type: 'xyzir'
    sensor_frame: 'lidar_1/os_sensor'
    lidar_frame: 'lidar_1/os_lidar'
    imu_frame: 'lidar_1/os_imu'
